### ISSUE TITLE
Question regarding TPC-H generated queries

### ISSUE THREAD

**Issue by nghiahhnguyen** [parimarjan/db-embedding-tools#1]
In your paper "Neo: A Learned Query Optimizer", it is mentioned that you and the other authors generated 80 training and 20 test queries for the TPC-H dataset. May I ask whether these queries are available? If it is, can you tell how I can get access to the queries?

**Comment by RyanMarcus** [comment]
Hi!

For TPC-H, we randomly sampled 80% of the templates into the training group, then put the remaining 20% of the templates into the test group (modulo rounding). Then we randomly sampled these templates with replacement until we'd reached the appropriate number of queries in each group.

You should be able to produce your own random samples using the TPC-H query generator tool.

Thanks,
Ryan
